### ISSUE TITLE
Upgrade from V3 to V9-Renault Talisman (R-Link2)

### ISSUE THREAD

**Issue by Goran-Barznje** [maniyar99/upgrade-software-from-Rlink2-for-talisman#1]
Once i upgraded from V3 to V9 i lost many things of my R- link 2 screen, so now i want to downgrade from V9 to V3

Much appreciated for your help ![image](https://user-images.githubusercontent.com/82806656/125491954-dbdf5b66-fe23-4edf-b346-d5a6290d4ae1.jpeg)![image](https://user-images.githubusercontent.com/82806656/125492002-4b520863-0a23-476c-985f-533aae80d84f.jpeg)

**Comment by alireza6631** [comment]
Hello
I also had this problem, nothing will be solved with the return
I have a suggestion, maybe you can upgrade the software boot
